# Generated by Django 5.2.13 on 2026-04-14 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemErrorLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('error_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('traceback', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
