# Generated by Django 5.2.13 on 2026-04-14 22:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADHDReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eeg_file', models.FileField(blank=True, null=True, upload_to='adhd_eeg/')),
                ('ai_full_response', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adhd_report', to='children.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ASDReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motion_video', models.FileField(blank=True, null=True, upload_to='asd_videos/motion/')),
                ('emotion_video', models.FileField(blank=True, null=True, upload_to='asd_videos/emotion/')),
                ('questionnaire_answers', models.JSONField(blank=True, null=True)),
                ('videos_ai_response', models.JSONField(blank=True, null=True)),
                ('physiology_file', models.FileField(blank=True, null=True, upload_to='asd_physiology/')),
                ('physiology_ai_response', models.JSONField(blank=True, null=True)),
                ('ai_full_response', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('recommendation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asd_report', to='children.childprofile')),
            ],
        ),
    ]
