# Generated by Django 5.2.13 on 2026-04-14 22:09

import children.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.CharField(default=children.models.generate_child_id, max_length=20, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('clinic_note', models.TextField(blank=True, null=True)),
                ('age_of_fw', models.PositiveIntegerField(blank=True, null=True)),
                ('age_of_sw', models.PositiveIntegerField(blank=True, null=True)),
                ('lost_skills', models.BooleanField(blank=True, null=True)),
                ('speech_level', models.CharField(blank=True, max_length=100, null=True)),
                ('gestures_use', models.PositiveIntegerField(blank=True, null=True)),
                ('diagnosed', models.CharField(blank=True, max_length=200, null=True)),
                ('hear_problem', models.BooleanField(blank=True, null=True)),
                ('vision_problem', models.BooleanField(blank=True, null=True)),
                ('fam_history', models.CharField(blank=True, max_length=300, null=True)),
                ('energy_level', models.PositiveIntegerField(blank=True, null=True)),
                ('sensitive_level', models.PositiveIntegerField(blank=True, null=True)),
                ('eeg_history', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorChildAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
