# Generated by Django 5.2.13 on 2026-04-14 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorchildaccess',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_doctors', to='children.childprofile'),
        ),
        migrations.AddField(
            model_name='doctorchildaccess',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessible_children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doctorchildaccess',
            unique_together={('doctor', 'child')},
        ),
    ]
