# Generated by Django 5.2.13 on 2026-04-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='age_of_fw',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='age_of_sw',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='diagnosed',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='energy_level',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='fam_history',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='gestures_use',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='hear_problem',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='lost_skills',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='sensitive_level',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='speech_level',
        ),
        migrations.RemoveField(
            model_name='childprofile',
            name='vision_problem',
        ),
        migrations.AddField(
            model_name='childprofile',
            name='basic_info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='behavior',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='dev_milestones',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='med_history',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
